server:
  port: 8080

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost/marketplace_user
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
